PROC IMPORT OUT= ICU
 DATAFILE= "Desktop\problem2abc\ICU.txt"
 DBMS=TAB REPLACE;
 GETNAMES=YES;
 DATAROW=2;


/*PROC PRINT DATA=ICU;
 VAR STA AGE CAN CPR INF RACE;*/

PROC LOGISTIC DATA=ICU;
 CLASS RACE(REF='1')/PARAM=REF;
 MODEL STA(EVENT='1')=AGE CAN CPR INF RACE/CLPARM=BOTH;
 CONTRAST 'RACE=0' RACE 1 0, RACE 0 1; 
 TITLE 'Problem 2.2 (a)(b)(c)';

RUN;
